# Generated by Django 2.0.4 on 2018-05-10 13:25

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='物品类别名称')),
                ('desc', models.CharField(max_length=20, verbose_name='详细描述')),
            ],
            options={
                'verbose_name': '回收类别表',
                'verbose_name_plural': '回收类别表',
            },
        ),
        migrations.CreateModel(
            name='RecycleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='数量')),
                ('time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('rcCate', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='app1.RecycleCategory', verbose_name='回收物品类别')),
            ],
            options={
                'verbose_name': '回收记录表',
                'verbose_name_plural': '回收记录表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=20, verbose_name='用户角色名称')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='回收点名称')),
                ('location', models.CharField(max_length=20, verbose_name='所在位置')),
                ('capacity', models.IntegerField(verbose_name='垃圾桶容量')),
                ('count', models.IntegerField(verbose_name='目前垃圾的数量')),
                ('recType', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='app1.RecycleCategory', verbose_name='回收类别')),
            ],
            options={
                'verbose_name': '回收点表',
                'verbose_name_plural': '回收点表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20, verbose_name='用户名')),
                ('userPassword', models.CharField(max_length=20, verbose_name='密码')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('number', models.CharField(max_length=10, verbose_name='学号')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('emailField', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('credit', models.IntegerField(default=0, verbose_name='公益积分')),
                ('score', models.IntegerField(default=0, verbose_name='团学积分')),
                ('donate', models.IntegerField(default=0, verbose_name='捐赠积分')),
                ('autoDonate', models.CharField(choices=[('是', '是'), ('否', '否')], default='否', max_length=1, verbose_name='积分是否自动捐赠')),
                ('disable', models.CharField(choices=[('是', '是'), ('否', '否')], default='否', max_length=1, verbose_name='冻结用户资格')),
                ('wxOpenId', models.CharField(max_length=50, verbose_name='微信OpenId')),
                ('role', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='app1.Role', verbose_name='用户角色')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AddField(
            model_name='recyclerecord',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='app1.Site', verbose_name='所在回收点'),
        ),
        migrations.AddField(
            model_name='recyclerecord',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='app1.User', verbose_name='用户编号'),
        ),
    ]
