# Generated by Django 2.0.4 on 2018-05-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wxOpenId',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='微信OpenId'),
        ),
    ]
