# Generated by Django 2.0.4 on 2018-05-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20180510_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recyclerecord',
            name='rcCate',
        ),
    ]
