# Generated by Django 2.0.4 on 2018-05-12 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_recyclerecord_rccate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclerecord',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Site', verbose_name='所在回收点'),
        ),
        migrations.AlterField(
            model_name='recyclerecord',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.User', verbose_name='用户编号'),
        ),
        migrations.AlterField(
            model_name='site',
            name='recType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.RecycleCategory', verbose_name='回收类别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Role', verbose_name='用户角色'),
        ),
    ]
