# Generated by Django 2.0.4 on 2018-05-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20180512_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclecategory',
            name='desc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='详细描述'),
        ),
    ]
