# Generated by Django 2.0.4 on 2018-05-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20180512_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='capacity',
            field=models.IntegerField(default=50, verbose_name='垃圾桶容量'),
        ),
        migrations.AlterField(
            model_name='site',
            name='count',
            field=models.IntegerField(default=0, verbose_name='目前垃圾的数量'),
        ),
        migrations.AlterField(
            model_name='site',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='所在位置'),
        ),
    ]
