# Generated by Django 2.0.4 on 2018-05-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20180512_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=20, verbose_name='回收点编号'),
        ),
    ]
