# Generated by Django 2.0.4 on 2018-05-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20180512_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userName',
        ),
        migrations.AlterField(
            model_name='recyclerecord',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
    ]
