# Generated by Django 2.0.5 on 2018-05-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20180514_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='denote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toatalNumber', models.IntegerField(default=0, verbose_name='总计捐赠分数')),
                ('toatalDes', models.CharField(max_length=50, verbose_name='描述')),
            ],
        ),
    ]
