# Generated by Django 2.0.5 on 2018-05-17 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_denote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='denote',
        ),
    ]
