# Generated by Django 2.0.5 on 2018-05-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_delete_denote'),
    ]

    operations = [
        migrations.CreateModel(
            name='denote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denoteUser', models.CharField(max_length=30, verbose_name='用户')),
                ('toatalNumber', models.IntegerField(default=0, verbose_name='总计捐赠分数')),
                ('denoteDes', models.CharField(max_length=50, verbose_name='描述')),
            ],
            options={
                'verbose_name': '总计捐赠分数',
                'verbose_name_plural': '总计捐赠分数',
            },
        ),
    ]
