# Generated by Django 2.0.5 on 2018-05-31 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_denote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=200, verbose_name='反馈信息')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='userPassword',
            field=models.CharField(default='000000', max_length=20, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.User', verbose_name='用户'),
        ),
    ]
